### PR TITLE
Add ActiveRecord translations support

### PR DESCRIPTION
**Pull request by hrom512**
Fix problem with translations for ActiveRecord attributes. For example:

``` ruby
class Song < ActiveRecord::Base
end

class SongForm < Reform::Form
  include Reform::Form::ActiveModel::Validations
  include Reform::Form::ActiveRecord

  property :title
end

# returns "Title" despite I18n translations
SongForm.human_attribute_name(:title)
```

### CODE REVIEW

**Comment by apotonick** [comment]
That's cool! However, it will be a breaking API change.

**Comment by zavan** [comment]
This can be closed, since `human_attribute_name` is now delegated to the model class: https://github.com/trailblazer/reform-rails/blob/749c8ae57a081a0f5a3c11684c94ac7cc68a831b/lib/reform/form/active_model/validations.rb#L21

**Comment by ValentinTrinque** [comment]
Where are we on this ? I encounter this very problem. How can we get this fixed ? I am wiling to help if needed.

**Comment by oliverguenther** [comment]
This still occurs even if your model or form defines `i18n_scope` due to the fact the the validator delegates to `AM::Naming` (https://github.com/trailblazer/reform-rails/blob/master/lib/reform/form/active_model/validations.rb#L141). 

Since we depend upon for accessing AR keys, opening the validator class to enforce the scope works - while not pretty - as expected:

``` ruby 
Reform::Form::ActiveModel::Validations::Validator.class_eval do
  ##
  # use activerecord as the base scope instead of 'activemodel' to be compatible
  # to the messages we have already stored
  def self.i18n_scope
    :activerecord
  end
end
```

What is needed to move this PR forward?

**Comment by apotonick** [comment]
The main problem is that this fix will break a lot of code since we "force" the correct i18n key. There should be a soft deprecation so we can undo this.

**Comment by apotonick** [comment]
Maybe an explicit `require "reform/active_record/i18n" or something?

**Comment by emaglio** [comment]
Really old PR which I'll close for now @hrom512, if you still using `reform-rails` could you please test `master` branch

**Pull request closed without merging**
